name: zqplayerflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0
  dio: ^3.0.8
  cached_network_image: ^2.0.0
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #这两个是dev的，不要放到上面去了哦
  build_runner: ^1.7.1
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - images/avatar_placeholder.png
    - images/white_right_arrow.png
    - images/black_arrow_right.png
